spring:
#指定dev文件启动
  profiles:
    active: dev

#禁用thymeleaf
  thymeleaf:
    cache: false

#redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: essm123456
    database: 0

#mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.essm.entity

#http设置
http:
  #最大连接数
  maxTotal: 100
  defaultMaxPerRoute: 20
  #连接超时时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
